export const POLLING_INTERVAL = process.env.NEXT_PUBLIC_LIGHTWEIGHT_MODE ? 7500000 : 7500
export const GLOBAL_POLLING_INTERVAL = process.env.NEXT_PUBLIC_LIGHTWEIGHT_MODE ? 500000 : 5000
export const IS_ETS_DOMAIN = process.env.NEXT_PUBLIC_IS_ETS_DOMAIN === 'true'
